### ISSUE TITLE
Installation description

### ISSUE THREAD

**Issue by mbuttner** [andreariba/DeepCycle#3]
Hi there,
I would love to try the DeepCycle on my data as it looks like the ideal model for me to get rid of the cell cycle influence I have. However, I am a bit at a loss with the `requirements` file and I would highly appreciate some more description on the installation. Trying to use the `requirements` file to create a `conda` environment did not work as every line in the file contained several `=` signs, which contradicted the required syntax.

**Comment by andreariba** [comment]
Hi,
I added the yml file 'DeepCycle_env.yml' storing the conda environment I used to develop and run DeepCycle.
Just run the following command:
conda env create -f DeepCycle_env.yml
(Sorry it's not the cleanest environment)

Otherwise, you can also create your own environment with the dependencies listed at the end of the README.
Let me know if you manage either ways

**Comment by andreariba** [comment]
without any further reply I consider this closed

**Comment by mbuttner** [comment]
Hi,
thanks for the quick reply - I was on holidays in August and haven't had time to try your `yml` file. It worked like a charm, thank you! 
I suggest that you add a short section about the installation in your readme, to help the next one who is eager to try out DeepCycle. I just realised that you have put the installation at the end of the readme - I would have expected it at the top 😅
