### ISSUE TITLE
Additional Functionality

### ISSUE THREAD

**Issue by bbraun923** [andreariba/DeepCycle#9]
Thank you for developing a fantastic tool! Two questions:

1) Can DeepCycle be used for other rhythmic cellular processes outside of cell cycle given a different list of known cycling input genes?

2) Is DeepCycle specific for single cell sequencing or can be applied to single nuclei sequencing data?

**Comment by andreariba** [comment]
Hi,

thanks for checking DeepCycle. Here my answers:

1. in principle, yes it can be used for other rhythmic processes, you have to change the list of genes accordingly. Just check that the genes in your list are expressed enough to detect both mature and pre-mRNAs. 

2. you can run it with whatever data (possibly normalized). DeepCycle should run fine. If you have problems, let me know or just open an issue if you encounter any error and I can tell you more.

**In both cases, remember to apply scvelo normalization with the function pp.moments to the Anndata before inputting the data to DeepCycle. Alternatevily, you can create an Anndata with the variables Ms and Mu like the one generated by scvelo without applying the normalization.**

Best,
Andrea

**Comment by bbraun923** [comment]
Thank you, Andrea! I was able to successfully run DeepCycle on my dataset; however, the program always uses/plot only ~10% of the input genes from gene list even though many unused genes are highly expressed. Do you know why the program filters out a majority of the input genes? Is there a way to extract cycling/non-cycling data from all input genes?

**Comment by andreariba** [comment]
it depends on how you're running deepcycle.

1. You can choose the expression threshold with the option --expression_threshold, to filter all the genes below that expression level you set.
2. Another option you can set is the hotelling filter (--hotelling), it selects genes showing more than one maximum in the expression levels (unspliced-spliced space). The hotelling filter is very strong, you can try disabling it, but it won't help the fitting procedure instead it will introduce a lot of noise from non-cycling genes.

So my guess is that you're losing a lot of genes because of the hotelling filter, but I don't think it's a good idea to disable it. Perhaps your dataset does not have enough cells having genes showing multiple states of expression.
